<?php
namespace app\index\model;
use think\Model;
class Advert extends Common
{
    public $tablename = "oson_advert";
    public function insert(array $data = [], $replace = false, $getLastInsID = false, $sequence = null)
    {
        return parent::insert($data, $replace, $getLastInsID, $sequence); // TODO: Change the autogenerated stub
    }
}